name: Release

on: repository_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.action == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: 'Leandro Lourenci'
          GIT_AUTHOR_EMAIL: 'leandro@lourenci.com'
          GIT_COMMITTER_NAME: 'Leandro Lourenci'
          GIT_COMMITTER_EMAIL: 'leandro@lourenci.com'
        run: yarn semantic-release
